### ISSUE TITLE
 ROIs cannot be selected by owner when importing/sending from/to OMERO

### ISSUE THREAD

**Issue by Rdornier** [qupath/qupath-extension-omero#44]
One request we had some time ago from our users was to be able to collaborate on the same image, and more particularly to annotate the same image but without seeing the annotations from another collaborator. This scenario occurred during a project on deep learning, where different collaborators had to independently annotate the same image, without biasing each other.

To do so, we have had introduced a feature to filter ROIs by owner, so that each collaboators is able to see, create and update their own 
annotations without being biased.
This feature was very useful and is still used for that kind of projects. It would very nice to also have it implemented there.

**Comment by Rylern** [comment]
Thanks, this should be fixed with [v0.1.0-rc6](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc6), please open the issue again if the problem persists.

**Comment by Rylern** [comment]
Thanks, this should be fixed with [v0.1.0-rc11](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc11), please open the issue again if the problem persists.

**Comment by Rdornier** [comment]
> the list of owners seems to not be filtered according to group permission

This is now fixed, thanks

> the measurements from all members are by default deleted on OMERO when we check the option. Maybe it could be worth to select from which owner we would like to delete the measurements.

I can now, select from which owner we would like to delete the measurements but...  attachments are actually not deleted even if we ask so and they pile-up in the attachment tab

**Comment by Rylern** [comment]
> I can now, select from which owner we would like to delete the measurements but... attachments are actually not deleted even if we ask so and they pile-up in the attachment tab

I wasn't able to reproduce that, can you give more details (debug logs, error dialogs)?

**Comment by Rdornier** [comment]
I just get this in debug mode
`Deleting all attachments added from QuPath to the class qupath.ext.omero.core.entities.repositoryentities.serverentities.image.Image with ID 39672`

I can still reproduce this error on the test server, when I'm logged-in with the demo user (right permission to delete, annotate etc), but cannot reproduce it on the production server :angry:

**Comment by Rylern** [comment]
Can you try again with [v0.1.0-rc12](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc12)? I didn't solve the issue but added a lot of logs, so we might get more information. You can even set the logger to `TRACE` as it'll show the raw HTTP response to the request.

**Comment by Rdornier** [comment]
Ok, I've activated the trace mode but I don't see anything obvious. The logs say that it deleted all attachments from QuPath but then, when it gets back annotations, the attachments are still present.

```
Deleting measurements of image with ID 39687 belonging to users [...]
Deleting all attachments added from QuPath to the class qupath.ext.omero.core.entities.repositoryentities.serverentities.image.Image with ID 39687 belonging to owners [...]
Getting OMERO annotations of the class qupath.ext.omero.core.entities.repositoryentities.serverentities.image.Image with ID 39687
[...]
Found annotation {[...]  Annotation owned by Owner of ID 355: Training User and added by Link[owner=Owner of ID 355: Training User]. Map: {id=235940, name=qupath_QP annotation table_testomerorc9_20250326-11h58m46.csv, size=950, path=qupath_QP annotation table_testomerorc9_20250326-11h58m46.csv, mimetype=text/csv}, [...]}

```

However, as it is an issue that I have only on a test server and only for a specific user, I don't think it's worth to dig more on that issue for the moment. I could also be due to internal server issues, as we are using this server to test and try a lot of things.

If the problem appears at some point in the production server, then we'll have a closer look.

**Comment by Rylern** [comment]
OK, please re-open the issue if it happens in the production server.
